repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^_freeze/
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      # Run Ruff linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      # Run Ruff formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]
