project:
  type: website

website:
  title: "learning-hd"
  site-url: https://hdigital.github.io/teaching/
  description: Things I learned
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml
format:
  html:
    theme: flatly
