project:
  type: website

website:
  title: "learning-hd"
  site-url: https://hdigital.github.io/learning-diary/
  description: Things I learned
  navbar:
    left:
      - about.qmd
    right:
      - icon: github
        href: https://github.com/hdigital/learning-diary/
      - icon: rss
        href: index.xml
format:
  html:
    theme: flatly
