FROM rocker/verse

WORKDIR /home/rstudio

# install Linux dependencies (required for Python, R, Quarto)
RUN apt-get -y update && apt-get install -y --no-install-recommends \
    curl \
    gdebi-core \
    python3 \
    python3-dev \
    python3-pip

# install Quarto
RUN curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb
RUN gdebi --non-interactive quarto-linux-amd64.deb

# install R packages
RUN install2.r \
    gapminder \
	markdown \
    patchwork \
	reticulate

# install Python packages
COPY requirements.txt .

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

ENV QUARTO_PYTHON="/usr/bin/python3"
