FROM jupyter/datascience-notebook

# install Quarto
USER root

RUN apt-get -y update && apt-get install -y --no-install-recommends gdebi-core
RUN curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb

RUN gdebi --non-interactive quarto-linux-amd64.deb

USER $NB_UID


WORKDIR /home/datascience
