FROM python:slim

# install Quarto
RUN apt-get -y update && apt-get install -y --no-install-recommends \
    curl \
    gdebi-core \
	r-cran-tidyverse

RUN curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb
RUN gdebi --non-interactive quarto-linux-amd64.deb

RUN python -m pip install --upgrade pip
RUN python -m pip install jupyterlab

workdir /home/jupyter

CMD jupyter lab --ip='*' --port=8888 --no-browser --allow-root
