FROM continuumio/anaconda3

# install Quarto
RUN apt-get -y update && apt-get install -y --no-install-recommends gdebi-core

RUN curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb
RUN gdebi --non-interactive quarto-linux-amd64.deb

ENV QUARTO_PYTHON="/usr/bin/python3"

# install R
RUN conda install -y --quiet \
    r-base \
    r-tidyverse

CMD /opt/conda/bin/jupyter lab --ip='*' --port=8888 --no-browser --allow-root
